### ISSUE TITLE
How do I use this ? The examples are way too complex ! I need to draw a triangle

### ISSUE THREAD

**Issue by GeorgeFlorian** [marcmerlin/SmartMatrix_GFX#1]
Hello !

As the title states, I need help understanding how does this library work...

I don't need fancy images or animations. I need to know how to **draw** a **line**, a **triangle**, how to **output** some **numbers**, how to change the font size.
But first I want to know what code is mandatory. What do I need to write in every project to be able to use it.

**How do I start it ?**

I want to keep it simple. Unfortunately, your examples are very complex and use a lot of methods and functions that I don't need and won't use.

Can you help me drawing a triangle ? Thank you !

**Comment by marcmerlin** [comment]
Have a look at 
https://github.com/marcmerlin/SmartMatrix_GFX/blob/master/examples/MatrixGFXDemo/MatrixGFXDemo.ino#L388
it does what you ask.
https://github.com/marcmerlin/SmartMatrix_GFX/blob/master/examples/MatrixGFXDemo/MatrixGFXDemo.ino#L408

For more, see https://learn.adafruit.com/adafruit-gfx-graphics-library/graphics-primitives
```
void drawTriangle(uint16_t x0, uint16_t y0, uint16_t x1, uint16_t y1, uint16_t x2, uint16_t y2, uint16_t color);
void fillTriangle(uint16_t x0, uint16_t y0, uint16_t x1, uint16_t y1, uint16_t x2, uint16_t y2, uint16_t color);
```

**Comment by GeorgeFlorian** [comment]
That is helpful, thank you ! But I know about Adafruit GFX Primitives.

What I don't get is if they'll work just as easy.

I still have some questions left. I don't know why you closed this. I believe it to be an issue when someone can't figure out how this library works.

When do we need to use the following line `matrixLayer.addLayer(&backgroundLayer);` ?

I don't understand what to use and what not to use from this: 
```
#define mw kMatrixWidth
#define mh kMatrixHeight
#define NUMMATRIX (kMatrixWidth*kMatrixHeight)

CRGB leds[kMatrixWidth*kMatrixHeight];

// Sadly this callback function must be copied around with this init code
void show_callback() {
    for (uint16_t y=0; y<kMatrixHeight; y++) {
	for (uint16_t x=0; x<kMatrixWidth; x++) {
	    CRGB led = leds[x + kMatrixWidth*y];
	    // rgb24 defined in MatrixComnon.h
	    backgroundLayer.drawPixel(x, y, { led.r, led.g, led.b } );
	}
    }
    // This should be zero copy
    // that said, copy or no copy is about the same speed in the end.
    backgroundLayer.swapBuffers(false);
}

SmartMatrix_GFX *matrix = new SmartMatrix_GFX(leds, mw, mh, show_callback);
```
