### ISSUE TITLE
How is MatrixGFXDemo.ino supposed to work ?

### ISSUE THREAD

**Issue by GeorgeFlorian** [marcmerlin/SmartMatrix_GFX#3]
Hello !

Here is how it looks on my display: https://youtu.be/TH8RKTCQJXA

Is this how it's supposed to work ?

Thank you !

**Comment by marcmerlin** [comment]
yes, this looks correct enough.

**Comment by marcmerlin** [comment]
I did update the code though as the one you had didn't have zero copy. This is now fixed.
But this should not affect you.
