### ISSUE TITLE
#include errors since the latest update

### ISSUE THREAD

**Issue by GeorgeFlorian** [marcmerlin/SmartMatrix_GFX#4]
Hello !
I've just updated the library and I have this error:
```
cannot open source file "Framebuffer_GFX.h" (dependency of "SmartMatrix_GFX.h")
```

I have no idea how to fix it.

I am using Platformio IDE. I've rebuild the IntelliSense Path multiple times but with no luck.

What do you think ?

Do I need another `#include <>` ?

**Comment by marcmerlin** [comment]
yes, as per the git changelog and https://github.com/marcmerlin/SmartMatrix_GFX/blob/master/README.md
you now need https://github.com/marcmerlin/Framebuffer_GFX
Most of the code was moved to the base library to avoid code repetition across 3 libraries that offer the same interface on 3 different hardware backends.

**Comment by marcmerlin** [comment]
https://www.google.com/search?q=Framebuffer_GFX.h&oq=Framebuffer_GFX.h
would also have given you the answer quicker than asking here :)
