### ISSUE TITLE
matrix->clear(); does not work.

### ISSUE THREAD

**Issue by GeorgeFlorian** [marcmerlin/SmartMatrix_GFX#5]
Board: ESP32

I have this in `void main()`
```

          matrix->setTextColor(LED_CYAN_HIGH);
          matrix->setFont(NULL);
          matrix->setCursor(1,0);
          matrix->print("Home page");
          matrix->setCursor(0,8);
          matrix->print("found at:");
          matrix->setCursor(0,16);
          matrix->setTextWrap(true);
          matrix->setTextColor(LED_PURPLE_HIGH);
          matrix->print(IP_copy);
          matrix->show();
```

and this code inside `void loop()`:
```
if(WiFi.status() != WL_CONNECTED) {
      matrix->clear();
      delay(1000);
      Serial.println("There is no WiFi Connection !");
    }
```

I am basically checking if I have a WiFi Connection. If I don't, I want the display to display nothing.

While the `Serial.println()` works, the `matrix->clear();` does not clear the text from the display.

**Comment by marcmerlin** [comment]
matrix->clear() only clears the framebuffer. You still need to run matrix->show to sync the framebuffer to the display

**Comment by GeorgeFlorian** [comment]
You are absolutely right ! Thank you !
