### ISSUE TITLE
fatal error: DMAChannel.h: No such file or directory

### ISSUE THREAD

**Issue by GeorgeFlorian** [marcmerlin/SmartMatrix_GFX#9]
I am trying to upload a working project into an ESP32. By working project I mean an actual working, finished and implemented project that worked on ESP32.

All of a sudden, it started returning missing headers. One of which is:
```
.pio/libdeps/esp32doit-devkit-v1/SmartMatrix3_ID948/src/SmartMatrix_Impl.h:26:24: fatal error: DMAChannel.h: No such file or directory
```

The only change I did was to update PIO and all of the projects libraries, this one included.

What could the issue be ?

I have reinstalled VSC and PlatformIO to maybe fix the pathing but to no avail.

**Comment by GeorgeFlorian** [comment]
I have no idea how but I had SmartMatrix library twice in the same project. One was the master branch, which does not include ESP32 support, and the other one (the working one: `SmartMatrix-teensylc`) was the teensylc branch. I deleted the one with the master branch and it all worked out.

I don't know what is it about posting issues. But I almost always find the answer by myself only after I post the issue.

**Comment by marcmerlin** [comment]
@GeorgeFlorian if you spend enough time writing up your question, and looking at why things don't work and explaining to someone what you did and why it didn't work, you usually end up solving your problem at least half the time :)
http://www.catb.org/~esr/faqs/smart-questions.html#idm368
